# Generated by Django 3.1.3 on 2020-11-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201103_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='url',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, height_field=100, upload_to='avatars', width_field=100),
        ),
    ]
