# Generated by Django 3.1.3 on 2020-11-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='picture',
            field=models.ImageField(upload_to='annouc_photos'),
        ),
    ]
